---
title: "클러스터링"
output: html_document
---

##### 거리함수 dist
###### 수치형 데이터 거리
```{r}
x <- matrix(rnorm(100, mean = 0, sd =1), nrow = 5, ncol =20)
x
dist(x, method = "euclidean")
```
빈칸에 있는 거리는 중복값이기 때문에 생략되어서 나타나짐
: 유클리디언 거리로 만들어진 값


다른 method
```{r}
x1 <- c(10,20,1,2,3,4)
y1 <- c(5,6,7,8,9,10)
```

1. euclidean
```{r}
(x1 - y1)^2
```
각각을 빼서 제곱한 값 : 6개가 나옴
```{r}
sqrt(sum((x1 - y1)^2))
```
더해서 루트를 씌우기

```{r}
dist(rbind(x1,y1), method ="euclidean")
```

2. manhattan
```{r}
sum(abs(x1-y1))
dist(rbind(x1,y1), method="manhattan")
```


###### 범주형 데이터 거리
1. binary data
```{r}
x2 <- c(0,1,1,1,1,1)
y2 <- c(0,0,1,1,0,1)
```

얘네는 수치형
```{r}
sqrt(sum((x2-y2)^2))
```

```{r}
dist(rbind(x2,y2), method = "binary")
```
같은 자리에 0인 애들을 제외하고 --> 첫번째 열 제외
1이 하나라도 있는 것들을 가지고 --> 3,4열
진짜로 똑같은 애들의 비율을 빼줌
1- 3/5 = 2/5 = 0.4 가 나옴


2. library(cluster)
```{r}
library(cluster)
```

```{r}
a<- c(20,"F",170,"STD")
b<- c(25,"M",178,"SD")
c<- c(37,"M",173,"WK")
d<- c(21,"F",162,"STD")
```

```{r}
people <- as.data.frame(rbind(a,b,c,d))
colnames(people) <- c("age","sex","height","job")
str(people)
```
벡터를 숫자와 문자열을 섞어서 만들었기 때문에

```{r}
people$age <- as.numeric(people$age)
```
팩터로 들어가있어서 수치와 시키면 1234이런 값이 나옴
문자로 바꾼 다음 그걸 수치로 변화시키는 걸 해줘야됨

```{r}
people$age <- as.numeric(as.character(people$age))
people$height <- as.numeric(as.character(people$height))
```

* gower
범주형 =: 데이터가 여러개 섞여있을때 쓰는 daisy
```{r}
daisy_dist <- daisy(people, metric = "gower", stand = FALSE)
daisy_dist
```




